/**
 * AudioDojo.js
 * Audio Dojo — listening-comprehension passages.
 *
 * Launched from the Dojo's Audio Practice slot via JPApp.launch('audiodojo').
 * A flashcard-sized "audio box" plays a pre-baked multi-paragraph passage
 * (data/<lvl>/audiostories/<slug>/passage.m4a, generated by generate-audio.mjs).
 * The box morphs into a waveform on play; a scrubbable playbar with paragraph
 * breakpoints lets the learner hunt for answers. On completion, MCQs appear:
 * pressing a question button plays the question AS AUDIO ONLY (via
 * JPShared.tts.speak — the question clip is baked from audiostory `q`), with
 * four WRITTEN answer options.
 *
 * Lifecycle mirrors Stories.js: start(container, config, exit, deepLinkId, opts).
 * Passage list comes from data/audiostories.index.json.
 *
 * Depends on:
 *   - window.getAssetUrl(config, path)     : asset URL resolver
 *   - window.JPShared.tts                  : question-clip playback
 */
window.AudioDojoModule = (function () {
  'use strict';

  let container = null;
  let config = null;
  let onExit = null;
  let list = [];
  let currentInfo = null;   // index entry {id, dir, file, ...}
  let currentData = null;   // loaded audiostory.json
  let currentIndex = 0;
  let audio = null;         // HTMLAudioElement for the passage
  let raf = 0;
  let completedOnce = false;
  let segmentEnd = null;    // when set, playback auto-pauses here (per-paragraph replay)

  function getCdnUrl(p) { return window.getAssetUrl ? window.getAssetUrl(config, p) : p; }

  // Render a paragraph's tokens with furigana/romaji via the shared renderer
  // (honors the reading-aid toggles). Falls back to plain jp text.
  function renderTokens(tokens, jp) {
    const rk = window.JPShared && window.JPShared.jpText;
    if (!rk || !Array.isArray(tokens) || !tokens.length) return esc(jp || '');
    try { return tokens.map((t) => rk.renderToken(t)).join(''); }
    catch (e) { return esc(jp || ''); }
  }

  function esc(s) {
    return String(s == null ? '' : s)
      .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;').replace(/'/g, '&#39;');
  }

  function fmtTime(t) {
    if (!isFinite(t) || t < 0) t = 0;
    const m = Math.floor(t / 60), s = Math.floor(t % 60);
    return m + ':' + (s < 10 ? '0' : '') + s;
  }

  // ── Boot ───────────────────────────────────────────────────────────────
  function start(containerElement, repoConfig, exitCallback, deepLinkId) {
    container = containerElement;
    config = repoConfig;
    onExit = exitCallback;
    injectStyles();
    initialize(deepLinkId);
  }

  function injectStyles() {
    if (document.getElementById('jp-audiodojo-styles')) return;
    const style = document.createElement('style');
    style.id = 'jp-audiodojo-styles';
    style.textContent = `
      .ad-container {
        font-family: var(--font-ui,'Schibsted Grotesk','Work Sans',system-ui,sans-serif);
        background: var(--washi,#f5f1e8); color: var(--ink,#1a1816);
        min-height:100vh; min-height:100dvh; width:100%;
      }
      .ad-header {
        background: var(--ink,#1a1816); color: var(--washi,#f5f1e8);
        padding: max(28px,env(safe-area-inset-top)) 18px 14px;
        display:flex; justify-content:space-between; align-items:center; gap:10px;
        position:sticky; top:0; z-index:10; border-bottom:1px solid oklch(1 0 0 / 0.1);
      }
      .ad-title { font-weight:700; font-size:1.05rem; flex:1; min-width:0; }
      .ad-nav { display:flex; gap:8px; }
      .ad-nav button {
        background: oklch(1 0 0 / 0.1); color: var(--washi,#f5f1e8); border:none;
        padding:8px 14px; border-radius:8px; cursor:pointer; font-size:0.85rem; font-weight:600;
      }
      @media (hover:hover){ .ad-nav button:hover { background: oklch(1 0 0 / 0.2); } }
      .ad-body { padding:20px 16px max(40px,env(safe-area-inset-bottom)); max-width:520px; margin:0 auto; }
      .ad-sub { text-align:center; color: var(--ink-3,oklch(0.55 0.012 60)); font-size:0.9rem; margin-bottom:18px; }

      /* selector */
      .ad-card {
        background:#fff; border:1px solid var(--hairline-2,oklch(0.22 0.012 60 / 0.06));
        border-radius:16px; padding:16px 18px; margin-bottom:12px; cursor:pointer;
        box-shadow:0 4px 14px rgba(0,0,0,0.04); display:flex; align-items:center; gap:14px;
        transition: transform 0.12s, box-shadow 0.12s;
      }
      @media (hover:hover){ .ad-card:hover { transform: translateY(-2px); box-shadow:0 8px 22px rgba(0,0,0,0.08); } }
      .ad-card:active { transform: scale(0.99); }
      .ad-card-glyph {
        width:46px; height:46px; border-radius:12px; flex-shrink:0;
        background: oklch(0.60 0.18 30 / 0.10); color: var(--vermilion,#c2410c);
        display:flex; align-items:center; justify-content:center; font-size:1.4rem;
        font-family: var(--font-jp-display, serif);
      }
      .ad-card-jp { font-weight:700; font-size:1.05rem; }
      .ad-card-en { color: var(--ink-3,oklch(0.55 0.012 60)); font-size:0.85rem; margin-top:2px; }

      /* audio box */
      .ad-box {
        position:relative; width:100%; height:150px; border-radius:18px;
        background: linear-gradient(160deg, var(--ink,#1a1816), oklch(0.30 0.02 60));
        display:flex; align-items:center; justify-content:center; overflow:hidden;
        box-shadow:0 8px 26px rgba(0,0,0,0.18); cursor:pointer;
      }
      .ad-play {
        width:64px; height:64px; border-radius:999px; border:none; cursor:pointer;
        background: var(--vermilion,#c2410c); color:#fff; font-size:1.5rem;
        display:flex; align-items:center; justify-content:center;
        box-shadow:0 6px 18px oklch(0.60 0.18 30 / 0.5); transition: transform 0.12s;
        z-index:2;
      }
      .ad-play:active { transform: scale(0.92); }
      .ad-wave { position:absolute; inset:0; width:100%; height:100%; }
      .ad-box.playing .ad-play { width:40px; height:40px; font-size:1rem; position:absolute; bottom:10px; right:10px; background: oklch(1 0 0 / 0.18); box-shadow:none; }

      /* playbar */
      .ad-bar-wrap { margin-top:14px; }
      .ad-bar {
        position:relative; height:10px; border-radius:999px;
        background: var(--hairline,oklch(0.22 0.012 60 / 0.14)); cursor:pointer;
      }
      .ad-bar-fill {
        position:absolute; left:0; top:0; bottom:0; width:0%;
        background: var(--vermilion,#c2410c); border-radius:999px; pointer-events:none;
      }
      .ad-tick {
        position:absolute; top:-3px; width:2px; height:16px;
        background: oklch(0.22 0.012 60 / 0.4); transform:translateX(-1px);
        cursor:pointer; z-index:2;
      }
      /* enlarge the tap target without changing the visual tick */
      .ad-tick::after { content:''; position:absolute; inset:-10px -7px; }
      @media (hover:hover){ .ad-tick:hover { background: var(--vermilion,#c2410c); } }
      .ad-time {
        display:flex; justify-content:space-between; margin-top:6px;
        font-size:0.72rem; color: var(--ink-3,oklch(0.55 0.012 60));
        font-family: var(--font-mono,ui-monospace,Menlo,monospace);
      }
      .ad-hint { text-align:center; color: var(--ink-3,oklch(0.55 0.012 60)); font-size:0.82rem; margin:16px 0 4px; font-style:italic; }

      /* questions */
      .ad-q-section { margin-top:22px; }
      .ad-q-section h3 { font-size:1rem; font-weight:700; margin:0 0 12px; }
      .ad-q {
        background:#fff; border:1px solid var(--hairline-2,oklch(0.22 0.012 60 / 0.06));
        border-radius:16px; padding:16px; margin-bottom:12px; box-shadow:0 4px 14px rgba(0,0,0,0.04);
      }
      .ad-q-play {
        background: oklch(0.60 0.18 30 / 0.08); border:1px solid oklch(0.60 0.18 30 / 0.22);
        color: var(--vermilion-ink,#9a330a); padding:8px 16px; border-radius:999px; cursor:pointer;
        font-size:0.85rem; font-weight:600; display:inline-flex; align-items:center; gap:6px; margin-bottom:12px;
      }
      @media (hover:hover){ .ad-q-play:hover { background: oklch(0.60 0.18 30 / 0.14); } }
      .ad-q-play:active { transform: scale(0.97); }
      .ad-q-opts { display:grid; gap:8px; }
      .ad-q-opt {
        text-align:left; padding:12px 14px; border-radius:12px;
        border:1.5px solid var(--hairline,oklch(0.22 0.012 60 / 0.12)); background: var(--washi-2,#efebe2);
        color: var(--ink,#1a1816); font-size:1rem; cursor:pointer; font-family:inherit;
        transition: border-color 0.12s, background 0.12s;
      }
      @media (hover:hover){ .ad-q-opt:hover:not(:disabled){ border-color: var(--vermilion,#c2410c); } }
      .ad-q-opt:disabled { cursor:default; }
      .ad-q-opt.correct { background: oklch(0.72 0.15 150 / 0.18); border-color: oklch(0.55 0.15 150); }
      .ad-q-opt.wrong { background: oklch(0.62 0.20 25 / 0.14); border-color: oklch(0.55 0.20 25); }
      .ad-q-explain {
        margin-top:10px; padding:10px 12px; border-radius:10px;
        background: var(--washi-2,#efebe2); font-size:0.85rem; color: var(--ink-2,oklch(0.32 0.012 60)); line-height:1.5;
      }
      .ad-cta {
        width:100%; padding:13px; border:none; border-radius:12px; cursor:pointer;
        background: var(--ink,#1a1816); color: var(--washi,#f5f1e8); font-weight:600; font-size:0.95rem; margin-top:6px;
      }

      /* transcript (revealed after completion) */
      .ad-transcript-toggle {
        display:none; width:100%; margin-top:14px; padding:11px; cursor:pointer;
        background: var(--washi-2,#efebe2); border:1px solid var(--hairline,oklch(0.22 0.012 60 / 0.12));
        border-radius:12px; font-family:inherit; font-size:0.88rem; font-weight:600; color: var(--ink-2,oklch(0.32 0.012 60));
      }
      .ad-transcript { margin-top:12px; }
      .ad-para {
        display:flex; gap:10px; align-items:flex-start;
        background:#fff; border:1px solid var(--hairline-2,oklch(0.22 0.012 60 / 0.06));
        border-radius:12px; padding:12px 14px; margin-bottom:8px;
      }
      .ad-para-play {
        flex-shrink:0; width:34px; height:34px; border-radius:50%; border:none; cursor:pointer;
        background: oklch(0.60 0.18 30 / 0.10); color: var(--vermilion,#c2410c); font-size:0.85rem;
      }
      @media (hover:hover){ .ad-para-play:hover { background: oklch(0.60 0.18 30 / 0.20); } }
      .ad-para-play.playing { background: var(--vermilion,#c2410c); color:#fff; }
      .ad-para-jp { flex:1; min-width:0; font-size:1.1rem; line-height:2.0; font-family: var(--font-jp, inherit); }
      .ad-para-en { font-size:0.82rem; color: var(--ink-3,oklch(0.55 0.012 60)); margin-top:4px; line-height:1.4; }

      .ad-empty, .ad-loading, .ad-error { text-align:center; padding:50px 20px; color: var(--ink-3,oklch(0.55 0.012 60)); }
      /* selector locked rows */
      .ad-card.locked { opacity:0.6; cursor:default; }
      .ad-card.locked .ad-card-glyph { background: var(--hairline,oklch(0.22 0.012 60 / 0.10)); color: var(--ink-3,oklch(0.55 0.012 60)); }
      .ad-card-lock { font-size:0.78rem; color: var(--vermilion-ink,#9a330a); margin-top:3px; font-weight:600; }
    `;
    document.head.appendChild(style);
  }

  // ── Data ───────────────────────────────────────────────────────────────
  async function initialize(deepLinkId) {
    container.innerHTML = '<div class="ad-container"><div class="ad-loading">聴 · loading…</div></div>';
    try {
      const url = getCdnUrl('data/audiostories.index.json') + '?t=' + Date.now();
      const res = await fetch(url);
      const data = await res.json();
      list = (data.audiostories || []).slice().sort((a, b) => (a.order || 0) - (b.order || 0));
    } catch (e) {
      list = [];
    }
    if (deepLinkId) {
      const i = list.findIndex((s) => s.id === deepLinkId);
      if (i >= 0) { currentIndex = i; return loadPassage(list[i]); }
    }
    renderSelector();
  }

  function renderSelector() {
    if (window.JPApp) window.JPApp.showTabBar();
    stopAudio();
    let html = '<div class="ad-container">' +
      '<header class="ad-header"><div class="ad-title">🎧 Audio Practice</div>' +
      '<div class="ad-nav"><button id="ad-exit">Exit</button></div></header>' +
      '<div class="ad-body">' +
      '<div class="ad-sub">Listen and answer. Scrub the waveform to find the details.</div>';
    const unlock = window.JPShared && window.JPShared.unlock;
    if (!list.length) {
      html += '<div class="ad-empty">No listening passages yet.</div>';
    } else {
      list.forEach((s, i) => {
        const locked = unlock ? !unlock.isAudioStoryUnlocked(s) : false;
        if (locked) {
          html += '<div class="ad-card locked">' +
            '<div class="ad-card-glyph">🔒</div>' +
            '<div><div class="ad-card-jp">' + esc(s.title) + '</div>' +
            '<div class="ad-card-lock">Finish Lesson ' + esc(s.unlocksAfter || '') + ' to unlock</div></div></div>';
        } else {
          html += '<div class="ad-card" data-idx="' + i + '">' +
            '<div class="ad-card-glyph">聴</div>' +
            '<div><div class="ad-card-jp">' + esc(s.title) + '</div>' +
            '<div class="ad-card-en">' + esc(s.englishTitle) + '</div></div></div>';
        }
      });
    }
    html += '</div></div>';
    container.innerHTML = html;
    document.getElementById('ad-exit').onclick = onExit;
    container.querySelectorAll('.ad-card[data-idx]').forEach((c) => {
      c.onclick = function () { currentIndex = parseInt(this.dataset.idx, 10); loadPassage(list[currentIndex]); };
    });
  }

  async function loadPassage(info) {
    stopAudio();
    currentInfo = info;
    completedOnce = false;
    container.innerHTML = '<div class="ad-container"><div class="ad-loading">聴 · loading…</div></div>';
    try {
      const url = getCdnUrl(info.dir + '/' + (info.file || 'audiostory.json')) + '?t=' + Date.now();
      const res = await fetch(url);
      const data = await res.json();
      currentData = data;
      renderPlayer(data);
    } catch (err) {
      container.innerHTML = '<div class="ad-container"><div class="ad-error"><strong>Could not load passage</strong><br>' +
        esc(err.message || String(err)) + '</div></div>';
    }
  }

  function renderPlayer(data) {
    if (window.JPApp) window.JPApp.hideTabBar();
    const questions = (data.comprehension && data.comprehension.questions) || [];
    let qHtml = '';
    questions.forEach((q, qi) => {
      qHtml += '<div class="ad-q" data-qi="' + qi + '">' +
        '<button class="ad-q-play" data-qi="' + qi + '">🔊 Question ' + (qi + 1) + '</button>' +
        '<div class="ad-q-opts">';
      (q.options || []).forEach((opt, oi) => {
        qHtml += '<button class="ad-q-opt" data-qi="' + qi + '" data-oi="' + oi + '">' + esc(opt) + '</button>';
      });
      qHtml += '</div>';
      if (q.explanation) qHtml += '<div class="ad-q-explain" hidden data-explain-for="' + qi + '">' + esc(q.explanation) + '</div>';
      qHtml += '</div>';
    });

    // Transcript (revealed after completion): each paragraph with furigana + en
    // and a per-paragraph replay button.
    const paras = data.paragraphs || [];
    let tHtml = '';
    paras.forEach((p, i) => {
      tHtml += '<div class="ad-para" data-pi="' + i + '">' +
        '<button class="ad-para-play" data-pi="' + i + '" aria-label="Replay paragraph ' + (i + 1) + '">▶</button>' +
        '<div><div class="ad-para-jp">' + renderTokens(p.tokens, p.jp) + '</div>' +
        (p.en ? '<div class="ad-para-en">' + esc(p.en) + '</div>' : '') +
        '</div></div>';
    });

    const prevDisabled = currentIndex <= 0 ? 'disabled' : '';
    const nextDisabled = currentIndex >= list.length - 1 ? 'disabled' : '';

    container.innerHTML = '<div class="ad-container">' +
      '<header class="ad-header"><div class="ad-title">' + esc(data.title || '') + '</div>' +
      '<div class="ad-nav">' +
        '<button id="ad-prev" ' + prevDisabled + '>←</button>' +
        '<button id="ad-next" ' + nextDisabled + '>→</button>' +
        '<button id="ad-list">≡</button><button id="ad-exit">Exit</button></div></header>' +
      '<div class="ad-body">' +
        '<div class="ad-sub">' + esc(data.englishTitle || '') + '</div>' +
        '<div class="ad-box" id="ad-box">' +
          '<button class="ad-play" id="ad-play" aria-label="Play">▶</button>' +
          '<canvas class="ad-wave" id="ad-wave"></canvas>' +
        '</div>' +
        '<div class="ad-bar-wrap" id="ad-bar-wrap" hidden>' +
          '<div class="ad-bar" id="ad-bar"><div class="ad-bar-fill" id="ad-bar-fill"></div></div>' +
          '<div class="ad-time"><span id="ad-cur">0:00</span><span id="ad-dur">' + fmtTime(data.audio && data.audio.dur) + '</span></div>' +
        '</div>' +
        '<div class="ad-hint" id="ad-hint">Tap play and listen. Questions appear when the passage finishes.</div>' +
        '<div class="ad-q-section" id="ad-q-section" hidden><h3>Questions</h3>' + qHtml +
          '<button class="ad-cta" id="ad-cta" hidden></button>' +
        '</div>' +
        '<button class="ad-transcript-toggle" id="ad-transcript-toggle">📄 Show transcript</button>' +
        '<div class="ad-transcript" id="ad-transcript" hidden>' + tHtml + '</div>' +
      '</div></div>';

    wirePlayer(data);
  }

  // ── Waveform ─────────────────────────────────────────────────────────────
  function drawWave() {
    const canvas = document.getElementById('ad-wave');
    if (!canvas || !currentData) return;
    const peaks = (currentData.audio && currentData.audio.peaks) || [];
    const dpr = window.devicePixelRatio || 1;
    const cw = canvas.clientWidth || canvas.parentElement.clientWidth;
    const ch = canvas.clientHeight || 150;
    if (canvas.width !== Math.round(cw * dpr)) { canvas.width = Math.round(cw * dpr); canvas.height = Math.round(ch * dpr); }
    const ctx = canvas.getContext('2d');
    const w = canvas.width, h = canvas.height;
    ctx.clearRect(0, 0, w, h);
    const n = peaks.length || Math.floor(cw / 3);
    const barW = w / n;
    const dur = (audio && audio.duration) || (currentData.audio && currentData.audio.dur) || 0;
    const progress = (audio && dur) ? (audio.currentTime / dur) : 0;
    for (let i = 0; i < n; i++) {
      const v = peaks.length ? peaks[i] : 0.12;            // flat baseline if no peaks yet
      const bh = Math.max(2 * dpr, v * h * 0.86);
      const x = i * barW;
      const played = (i / n) <= progress;
      ctx.fillStyle = played ? 'rgba(194,65,12,0.95)' : 'rgba(245,241,232,0.32)';
      ctx.fillRect(x + barW * 0.15, (h - bh) / 2, barW * 0.7, bh);
    }
  }

  function loop() {
    // Per-paragraph replay: auto-pause at the segment boundary.
    if (audio && segmentEnd != null && isFinite(segmentEnd) && audio.currentTime >= segmentEnd - 0.03) {
      audio.pause();
      segmentEnd = null;
      clearParaPlaying();
    }
    drawWave();
    updateProgressUi();
    if (audio && !audio.paused && !audio.ended) raf = requestAnimationFrame(loop);
  }

  function updateProgressUi() {
    if (!audio) return;
    const dur = audio.duration || (currentData.audio && currentData.audio.dur) || 0;
    const fill = document.getElementById('ad-bar-fill');
    const cur = document.getElementById('ad-cur');
    if (fill && dur) fill.style.width = (audio.currentTime / dur * 100) + '%';
    if (cur) cur.textContent = fmtTime(audio.currentTime);
  }

  function placeTicks(data) {
    const bar = document.getElementById('ad-bar');
    const dur = (data.audio && data.audio.dur) || 0;
    const bps = (data.audio && data.audio.breakpoints) || [];
    if (!bar || !dur) return;
    bps.forEach((bp) => {
      if (bp <= 0) return;
      const tick = document.createElement('div');
      tick.className = 'ad-tick';
      tick.style.left = (bp / dur * 100) + '%';
      tick.title = 'Jump to this paragraph';
      // Snap-to-breakpoint: tapping a tick jumps to that paragraph's start.
      // stopPropagation so the bar's free-scrub handler doesn't also fire.
      tick.addEventListener('pointerdown', (e) => { e.stopPropagation(); seekTo(bp); });
      bar.appendChild(tick);
    });
  }

  // Seek to an absolute time (cancels any active segment-replay).
  function seekTo(t) {
    if (!audio) return;
    const dur = audio.duration || (currentData && currentData.audio && currentData.audio.dur) || 0;
    segmentEnd = null;
    audio.currentTime = Math.max(0, Math.min(t, dur || 0));
    if (audio.paused) audio.play().catch(() => {});
    updateProgressUi();
    drawWave();
  }

  // Per-paragraph replay: play just segment i (breakpoints[i] → breakpoints[i+1]).
  function playSegment(i) {
    if (!audio || !currentData) return;
    const bps = (currentData.audio && currentData.audio.breakpoints) || [];
    const dur = audio.duration || (currentData.audio && currentData.audio.dur) || 0;
    const start = bps[i] || 0;
    segmentEnd = (i + 1 < bps.length) ? bps[i + 1] : (dur || Infinity);
    audio.currentTime = start;
    document.querySelectorAll('.ad-para-play').forEach((b) => {
      b.classList.toggle('playing', parseInt(b.dataset.pi, 10) === i);
    });
    audio.play().catch(() => {});
  }

  function clearParaPlaying() {
    document.querySelectorAll('.ad-para-play.playing').forEach((b) => b.classList.remove('playing'));
  }

  // ── Wiring ───────────────────────────────────────────────────────────────
  function wirePlayer(data) {
    document.getElementById('ad-exit').onclick = onExit;
    document.getElementById('ad-list').onclick = renderSelector;
    const prev = document.getElementById('ad-prev');
    const next = document.getElementById('ad-next');
    if (prev) prev.onclick = () => { if (currentIndex > 0) { currentIndex--; loadPassage(list[currentIndex]); } };
    if (next) next.onclick = () => { if (currentIndex < list.length - 1) { currentIndex++; loadPassage(list[currentIndex]); } };

    const box = document.getElementById('ad-box');
    const playBtn = document.getElementById('ad-play');
    const barWrap = document.getElementById('ad-bar-wrap');
    const bar = document.getElementById('ad-bar');
    const hint = document.getElementById('ad-hint');
    const qSection = document.getElementById('ad-q-section');

    const src = getCdnUrl(currentInfo.dir + '/' + ((data.audio && data.audio.file) || 'passage.m4a'));
    audio = new Audio();
    audio.preload = 'auto';
    audio.src = src;

    function revealQuestions() {
      if (qSection) qSection.hidden = false;
      var tt = document.getElementById('ad-transcript-toggle');
      if (tt) tt.style.display = 'block';   // transcript becomes available on completion
      completedOnce = true;
    }

    function setPlaying(p) {
      if (box) box.classList.toggle('playing', p);
      if (playBtn) playBtn.textContent = p ? '⏸' : '▶';
    }

    audio.onplay = function () {
      setPlaying(true);
      if (barWrap) barWrap.hidden = false;
      placeTicksOnce(data);
      cancelAnimationFrame(raf); raf = requestAnimationFrame(loop);
    };
    audio.onpause = function () { setPlaying(false); drawWave(); clearParaPlaying(); };
    audio.onended = function () { setPlaying(false); updateProgressUi(); drawWave(); revealQuestions(); if (hint) hint.textContent = 'Scrub the waveform to re-listen, then answer below.'; };
    audio.onerror = function () {
      // Audio not generated yet (or failed to load): keep the flow testable by
      // revealing questions and noting the pending state.
      if (hint) hint.textContent = 'Audio is being prepared — run npm run gen:audio to bake it.';
      revealQuestions();
    };
    audio.onloadedmetadata = function () {
      const d = document.getElementById('ad-dur');
      if (d) d.textContent = fmtTime(audio.duration);
    };

    let ticksPlaced = false;
    function placeTicksOnce() { if (!ticksPlaced) { placeTicks(data); ticksPlaced = true; } }

    function toggle() {
      if (!audio) return;
      if (audio.paused) { segmentEnd = null; clearParaPlaying(); audio.play().catch(() => { if (audio.onerror) audio.onerror(); }); }
      else audio.pause();
    }
    if (playBtn) playBtn.onclick = (e) => { e.stopPropagation(); toggle(); };
    if (box) box.onclick = toggle;

    // Transcript toggle (shown on completion) + per-paragraph replay.
    var transcriptToggle = document.getElementById('ad-transcript-toggle');
    var transcript = document.getElementById('ad-transcript');
    if (transcriptToggle && transcript) {
      transcriptToggle.onclick = function () {
        var show = transcript.hidden;
        transcript.hidden = !show;
        transcriptToggle.textContent = show ? '📄 Hide transcript' : '📄 Show transcript';
      };
    }
    container.querySelectorAll('.ad-para-play').forEach(function (b) {
      b.onclick = function () { playSegment(parseInt(b.dataset.pi, 10)); };
    });

    function seekFromEvent(e) {
      if (!audio) return;
      segmentEnd = null; clearParaPlaying();   // free scrub cancels segment-replay
      const rect = bar.getBoundingClientRect();
      const clientX = (e.touches && e.touches[0]) ? e.touches[0].clientX : e.clientX;
      const ratio = Math.max(0, Math.min(1, (clientX - rect.left) / rect.width));
      const dur = audio.duration || (data.audio && data.audio.dur) || 0;
      if (dur) { audio.currentTime = ratio * dur; updateProgressUi(); drawWave(); }
    }
    if (bar) {
      bar.addEventListener('pointerdown', (e) => { bar.setPointerCapture && bar.setPointerCapture(e.pointerId); seekFromEvent(e); });
      bar.addEventListener('pointermove', (e) => { if (e.buttons) seekFromEvent(e); });
    }

    // Question audio + MCQ scoring.
    const questions = (data.comprehension && data.comprehension.questions) || [];
    container.querySelectorAll('.ad-q-play').forEach((btn) => {
      btn.onclick = function () {
        const qi = parseInt(this.dataset.qi, 10);
        const q = questions[qi];
        if (!q || !window.JPShared || !window.JPShared.tts) return;
        if (audio && !audio.paused) audio.pause();   // don't overlap passage + question
        window.JPShared.tts.speak(q.q);
      };
    });

    let answered = 0, correct = 0;
    const total = questions.length;
    container.querySelectorAll('.ad-q-opt').forEach((btn) => {
      btn.onclick = function () {
        const qi = parseInt(this.dataset.qi, 10);
        const oi = parseInt(this.dataset.oi, 10);
        const q = questions[qi];
        const wrap = container.querySelector('.ad-q[data-qi="' + qi + '"]');
        if (!wrap || wrap.dataset.answered) return;
        wrap.dataset.answered = '1';
        answered++;
        if (oi === q.correct) correct++;
        wrap.querySelectorAll('.ad-q-opt').forEach((b, idx) => {
          b.disabled = true;
          if (idx === q.correct) b.classList.add('correct');
          else if (idx === oi) b.classList.add('wrong');
        });
        const ex = wrap.querySelector('.ad-q-explain');
        if (ex) ex.hidden = false;
        if (answered === total) showCta(correct, total);
      };
    });

    function showCta(score, totalQ) {
      const cta = document.getElementById('ad-cta');
      if (!cta) return;
      cta.hidden = false;
      const hasNext = currentIndex < list.length - 1;
      cta.textContent = hasNext
        ? score + '/' + totalQ + ' correct — next passage →'
        : score + '/' + totalQ + ' correct — nice!';
      cta.onclick = () => {
        if (hasNext) { currentIndex++; loadPassage(list[currentIndex]); }
        else renderSelector();
      };
    }
  }

  function stopAudio() {
    segmentEnd = null;
    if (raf) { cancelAnimationFrame(raf); raf = 0; }
    if (audio) {
      try { audio.pause(); } catch (e) {}
      audio.onplay = audio.onpause = audio.onended = audio.onerror = audio.onloadedmetadata = null;
      try { audio.removeAttribute('src'); audio.load(); } catch (e) {}
      audio = null;
    }
    if (window.JPShared && window.JPShared.tts) window.JPShared.tts.cancel();
  }

  return { start: start };
})();
