#!/usr/bin/env node
// Vendors the Latin display font families used by the app into ./fonts as
// self-hosted woff2 + generates app/shared/fonts.css. Japanese text is left to
// the iOS/macOS system fonts (Hiragino), so Noto JP is intentionally NOT
// bundled (it would pull ~870 subset files). Re-run to refresh: node scripts/vendor-fonts.mjs
import { mkdir, writeFile, rm } from 'node:fs/promises';
import { join } from 'node:path';

const ROOT = new URL('..', import.meta.url).pathname;
const FONT_DIR = join(ROOT, 'fonts');
const OUT_CSS = join(ROOT, 'app', 'shared', 'fonts.css');

const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';

// Latin UI/display families only. JP (Noto Sans/Serif JP) falls back to system.
const FAMILIES = [
  'Schibsted+Grotesk:wght@400;500;600;700',
  'JetBrains+Mono:wght@400;500',
  'Caveat:wght@500;600;700',
];

const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');

async function fetchCss(family) {
  const url = `https://fonts.googleapis.com/css2?family=${family}&display=swap`;
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`CSS fetch failed ${res.status} for ${family}`);
  return res.text();
}

async function main() {
  await rm(FONT_DIR, { recursive: true, force: true });
  await mkdir(FONT_DIR, { recursive: true });

  let css = '/* Auto-generated by scripts/vendor-fonts.mjs — do not edit by hand. */\n';
  css += '/* Latin families self-hosted for offline use. Japanese falls back to system (Hiragino on iOS/macOS). */\n\n';
  let total = 0;

  for (const family of FAMILIES) {
    const famName = family.split(':')[0].replace(/\+/g, ' ');
    const raw = await fetchCss(family);
    const blocks = raw.split('@font-face').slice(1);
    let idx = 0;

    for (const blk of blocks) {
      const m = blk.match(/url\((https:\/\/[^)]+\.woff2)\)/);
      if (!m) continue;
      const remote = m[1];
      const weight = (blk.match(/font-weight:\s*([0-9]+)/) || [])[1] || '400';
      const style = (blk.match(/font-style:\s*([a-z]+)/) || [])[1] || 'normal';
      const fname = `${slug(famName)}-${weight}-${style}-${idx++}.woff2`;

      const fres = await fetch(remote, { headers: { 'User-Agent': UA } });
      if (!fres.ok) throw new Error(`woff2 fetch failed ${fres.status} ${remote}`);
      await writeFile(join(FONT_DIR, fname), Buffer.from(await fres.arrayBuffer()));
      total++;

      const rewritten = ('@font-face' + blk.slice(0, blk.indexOf('}') + 1))
        .replace(/url\(https:\/\/[^)]+\.woff2\)/, `url(../../fonts/${fname})`);
      css += rewritten.trim() + '\n\n';
    }
    console.log(`vendored ${famName}`);
  }

  await writeFile(OUT_CSS, css);
  console.log(`Done: ${total} woff2 files -> fonts/, css -> app/shared/fonts.css`);
}

main().catch((e) => { console.error(e); process.exit(1); });
