#!/usr/bin/env node
// Vendors the app's font families into ./fonts as self-hosted woff2 + generates
// app/shared/fonts.css. Re-run to refresh: node scripts/vendor-fonts.mjs
//
// Latin families are vendored whole. Japanese (Noto Sans/Serif JP) is SUBSET to
// exactly the characters that appear in the app's content (data/ + shared/), plus
// all kana, JP punctuation, and ASCII — via Google Fonts' `text=` param. That
// turns ~870 full subset files into a handful of small ones with REAL weights,
// so kanji no longer faux-bold on devices without Noto. Rare/compose glyphs
// outside the subset fall back to the system font (still fine — see
// font-synthesis:none in jp-text.css).
import { mkdir, writeFile, rm, readFile, readdir, stat } from 'node:fs/promises';
import { join } from 'node:path';
import { execFileSync } from 'node:child_process';
import { tmpdir } from 'node:os';

const ROOT = new URL('..', import.meta.url).pathname;
const FONT_DIR = join(ROOT, 'fonts');
const OUT_CSS = join(ROOT, 'app', 'shared', 'fonts.css');

const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';

// Latin UI/display families — vendored whole.
const FAMILIES = [
  'Schibsted+Grotesk:wght@400;500;600;700',
  'JetBrains+Mono:wght@400;500',
  'Caveat:wght@500;600;700',
];

// Japanese families — variable fonts SUBSET to the app's character set with
// fontTools (keeps the wght axis → real weights in one ~0.5MB file each).
// Requires: python3 + `pip install fonttools brotli`.
const JP_FONTS = [
  { name: 'Noto Sans JP',  file: 'noto-sans-jp',  ttf: 'https://github.com/google/fonts/raw/main/ofl/notosansjp/NotoSansJP%5Bwght%5D.ttf' },
  { name: 'Noto Serif JP', file: 'noto-serif-jp', ttf: 'https://github.com/google/fonts/raw/main/ofl/notoserifjp/NotoSerifJP%5Bwght%5D.ttf' },
];

const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');

// Collect every distinct character that appears in app content, then add full
// kana / JP punctuation / ASCII so mixed and dynamic strings still render.
async function buildJpText() {
  const chars = new Set();
  async function walk(dir) {
    let entries; try { entries = await readdir(dir); } catch { return; }
    for (const name of entries) {
      const p = join(dir, name);
      const st = await stat(p);
      if (st.isDirectory()) await walk(p);
      else if (name.endsWith('.json')) {
        const txt = await readFile(p, 'utf8');
        for (const ch of txt) if (ch.codePointAt(0) >= 0x2000) chars.add(ch);
      }
    }
  }
  await walk(join(ROOT, 'data'));
  await walk(join(ROOT, 'shared'));
  // Always include: ASCII, full hiragana + katakana, the prolonged-sound mark,
  // and common CJK/fullwidth punctuation — cheap insurance for dynamic text.
  for (let c = 0x20; c <= 0x7e; c++) chars.add(String.fromCodePoint(c));
  for (let c = 0x3040; c <= 0x30ff; c++) chars.add(String.fromCodePoint(c)); // kana
  for (let c = 0x3000; c <= 0x303f; c++) chars.add(String.fromCodePoint(c)); // CJK punct
  for (let c = 0xff00; c <= 0xffef; c++) chars.add(String.fromCodePoint(c)); // fullwidth
  return Array.from(chars).join('');
}

async function fetchCss(family, text) {
  let url = `https://fonts.googleapis.com/css2?family=${family}&display=swap`;
  if (text) url += `&text=${encodeURIComponent(text)}`;
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`CSS fetch failed ${res.status} for ${family}`);
  return res.text();
}

async function main() {
  await rm(FONT_DIR, { recursive: true, force: true });
  await mkdir(FONT_DIR, { recursive: true });

  let css = '/* Auto-generated by scripts/vendor-fonts.mjs — do not edit by hand. */\n';
  css += '/* Latin families vendored whole; Japanese (Noto) subset to the app\'s characters. */\n\n';
  const counts = { total: 0 };

  async function vendorFamily(family, text) {
    const famName = family.split(':')[0].replace(/\+/g, ' ');
    const raw = await fetchCss(family, text);
    const blocks = raw.split('@font-face').slice(1);
    let idx = 0;
    for (const blk of blocks) {
      const m = blk.match(/url\((https:\/\/[^)]+\.woff2)\)/);
      if (!m) continue;
      const remote = m[1];
      const weight = (blk.match(/font-weight:\s*([0-9]+)/) || [])[1] || '400';
      const style = (blk.match(/font-style:\s*([a-z]+)/) || [])[1] || 'normal';
      const fname = `${slug(famName)}-${weight}-${style}-${idx++}.woff2`;

      const fres = await fetch(remote, { headers: { 'User-Agent': UA } });
      if (!fres.ok) throw new Error(`woff2 fetch failed ${fres.status} ${remote}`);
      const buf = Buffer.from(await fres.arrayBuffer());
      await writeFile(join(FONT_DIR, fname), buf);
      counts.total++;

      const rewritten = ('@font-face' + blk.slice(0, blk.indexOf('}') + 1))
        .replace(/url\(https:\/\/[^)]+\.woff2\)/, `url(../../fonts/${fname})`);
      css += rewritten.trim() + '\n\n';
    }
    console.log(`vendored ${famName}${text ? ' (subset ' + idx + ' file' + (idx === 1 ? '' : 's') + ')' : ''}`);
  }

  for (const family of FAMILIES) await vendorFamily(family);

  // Japanese: subset the variable Noto fonts to the app's characters.
  const jpText = await buildJpText();
  const charFile = join(tmpdir(), 'jp-subset-chars.txt');
  await writeFile(charFile, jpText);
  console.log(`JP subset: ${[...jpText].length} chars`);
  for (const jp of JP_FONTS) {
    const ttfPath = join(tmpdir(), jp.file + '.ttf');
    const res = await fetch(jp.ttf, { headers: { 'User-Agent': UA } });
    if (!res.ok) throw new Error(`TTF fetch failed ${res.status} for ${jp.name}`);
    await writeFile(ttfPath, Buffer.from(await res.arrayBuffer()));
    const outName = `${jp.file}-variable.woff2`;
    execFileSync('python3', ['-m', 'fontTools.subset', ttfPath,
      `--text-file=${charFile}`, `--output-file=${join(FONT_DIR, outName)}`,
      '--flavor=woff2', '--layout-features=*', '--recommended-glyphs'], { stdio: 'pipe' });
    // Variable font → declare the full wght range so 400/500/600/700 all resolve
    // to a real weight (no synthetic bold).
    css += `@font-face {\n  font-family: '${jp.name}';\n  font-style: normal;\n  font-weight: 100 900;\n  font-display: swap;\n  src: url(../../fonts/${outName}) format('woff2');\n}\n\n`;
    counts.total++;
    console.log(`vendored ${jp.name} (variable subset)`);
  }

  await writeFile(OUT_CSS, css);
  console.log(`Done: ${counts.total} woff2 files -> fonts/, css -> app/shared/fonts.css`);
}

main().catch((e) => { console.error(e); process.exit(1); });
